name: kovri
version: master
summary: The Kovri I2P Router Project
description: |
  Kovri is a security-focused, community-driven C++ implementation of I2P

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  kovri:
    command: kovri-wrapper
    plugs: [network, network-bind]

parts:
  kovri:
    source: .
    source-type: git
    plugin: make
    build-packages:
      - g++
      - cmake
      - libboost-all-dev
      - libssl-dev
      - libssl1.0.0
    artifacts:
      - build/kovri
      - pkg/config
      - pkg/client
    organize:
      build/kovri: bin/
      pkg/*: .
  wrapper:
    plugin: dump
    source: snap/
    stage: [kovri-wrapper]
